app:
    resource: "@CTOAppBundle/Controller/"
    type:     annotation
dashboard:
    resource: "@CTOAppBundle/Controller/DashboardControllers/"
    type:     annotation
    prefix:   "admin"
api:
    resource: "@CTOAppBundle/Controller/ApiControllers/"
    type:     annotation
    prefix:   "api"

login_check:
    path: /login_check
logout:
    path: /logout