<?php

namespace CTO\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecommendationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RecommendationRepository extends EntityRepository
{
}
